### ISSUE TITLE
Add Support for Retrieving ETH Transaction Receipt

### ISSUE THREAD

**Issue by avislash** [nanmu42/etherscan-api#61]
Add support for being able to retrieve an ETH Transaction Receipt (https://docs.etherscan.io/api-endpoints/geth-parity-proxy#eth_gettransactionreceipt)

**Comment by nanmu42** [comment]
Thanks for your contribution.

However, [I had some doubt on our little package can handle `proxy` methods well](https://github.com/nanmu42/etherscan-api/issues/5#issuecomment-449684321).

Adding `proxy` methods would top-on much complexness and gotchas, as it speaks basically another language, with different API behavior, number representation and quirkers.

I would leave `proxy` methods out to keep the package simple and slim because of my limited maintenance power.

Your contribution does not come out in vain, it will always inspire and help people in the similiar needs. :)

**Comment by nanmu42** [comment]
Also closes #62 .

**Comment by avislash** [comment]
@nanmu42, I can respect your decision, however, I do need the proxy methods to be able to query the blockchain via Etherscan in order to get transaction receipts. Adding it to the library this way I don't need to use multiple services/API keys. I'll keep my fork up to facilitate my work in that regard and I'll push PRs back to this branch for future contributions.

**Comment by nanmu42** [comment]
Thanks for your understanding.
